export const ARGS_PREFIX = '--';
export const SEPARATOR = '=';
export const LINE_START_SYMBOL = '> ';
export const USERNAME_TEMPLATE = 'username';
export const GREETING_MSG = 'Welcome to the File Manager';
export const GOODBYE_MSG = 'Thank you for using File Manager';
export const INCORRECT_NAME_FORMAT_MSG = 'Please enter name in correct format: "--username=Your_name"';
export const ACTION_PROCEED = 'proceed';
export const ACTION_SHUTDOWN = 'shutdown';
export const EXIT_WORD = '.exit';
export const OPERATION_FAILED_TEXT = 'Operation failed';
